<a href="https://colab.research.google.com/github/kanishk014/stock-price-movement-prediction/blob/main/StockPriceMovementPrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import Libraries

In [83]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Reading Training Dataset

In [84]:
df = pd.read_csv('train.csv')
df.head()

exchange        RSI RSI_signal       ATR  EMA_relative  MA_relative  \
0      BigStock  60.176991       Hold  0.001340      0.999133     0.998415   
1    HeroStocks  30.000000        Buy  0.009333      0.999927     0.999907   
2   OkayFinance  45.454545       Hold  0.000107      0.998123     0.997812   
3  BubbleStocks  61.111111       Hold  0.000207      0.998539     0.998178   
4   OkayFinance  66.666667       Hold  0.192000      0.998542     0.998191   

   SMA_relative  WMA_relative      MACD  MACD_relative  ...  Bollinger_signal  \
0      0.158790      0.000696  0.000654       0.000990  ...              Hold   
1      0.009270      0.000069 -0.007056      -0.000058  ...              Hold   
2      0.219298      0.001863 -0.000028      -0.000611  ...              Hold   
3      0.182580      0.001528  0.000053       0.000260  ...              Hold   
4      0.181218      0.001477  0.140812       0.001585  ...              Hold   

   ichimoku_c_conversion_line  ichimoku_c_base_line  \
0                   -0.166616             -0.181763   
1                   -0.012268             -0.024536   
2                   -0.328228             -0.109409   
3                   -0.231877             -0.183061   
4                   -0.140734             -0.613601   

   ichimoku_c_leading_span_a  ichimoku_c_leading_span_b  ichimoku_c_signal  \
0                  -0.602090                  -0.446834               Sell   
1                  -0.292386                  -0.155394               Sell   
2                   0.109409                  -0.656455                Buy   
3                  -0.170857                  -0.414938                Buy   
4                  -0.529160                   1.339788               Sell   

   SAR_relative s&p_move_15m  result      id  
0     -0.136418     0.252291       2  573919  
1     -0.006776     0.062449       2  292589  
2     -0.143955     0.616755       1   80399  
3     -0.192382     0.343096       1  109870  
4     -0.199855    -0.352336       2  289641  

[5 rows x 40 columns]

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 490646 entries, 0 to 490645
Data columns (total 40 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   exchange                    490646 non-null  object 
 1   RSI                         490646 non-null  float64
 2   RSI_signal                  490646 non-null  object 
 3   ATR                         490646 non-null  float64
 4   EMA_relative                490646 non-null  float64
 5   MA_relative                 490646 non-null  float64
 6   SMA_relative                490646 non-null  float64
 7   WMA_relative                490646 non-null  float64
 8   MACD                        490646 non-null  float64
 9   MACD_relative               490646 non-null  float64
 10  MACD_relative_signal        490646 non-null  float64
 11  MACD_relative_histogram     490646 non-null  float64
 12  ADX                         490646 non-null  float64
 13  Stoch_O_k_valu

In [86]:
df.shape

(490646, 40)

In [87]:
df.isnull().sum()

exchange                      0
RSI                           0
RSI_signal                    0
ATR                           0
EMA_relative                  0
MA_relative                   0
SMA_relative                  0
WMA_relative                  0
MACD                          0
MACD_relative                 0
MACD_relative_signal          0
MACD_relative_histogram       0
ADX                           0
Stoch_O_k_value               0
Stoch_O_k_smoothed            0
Stoch_O_d_value               0
Stoch_O_signal_value          0
Stoch_O_signal                0
pivot_point                   0
pivot_support_1               0
pivot_resistance_1            0
pivot_support_2               0
pivot_resistance_2            0
pivot_support_3               0
pivot_resistance_3            0
fibonacci_signal              0
VWAP_relative_short           0
VWAP_relative_long            0
Bollinger_upper_band          0
Bollinger_lower_band          0
Bollinger_signal              0
ichimoku

#Data Preprocessing

## Dropping null values data rows

In [88]:
df = df.dropna()

In [89]:
df

exchange        RSI RSI_signal       ATR  EMA_relative  \
0           BigStock  60.176991       Hold  0.001340      0.999133   
1         HeroStocks  30.000000        Buy  0.009333      0.999927   
2        OkayFinance  45.454545       Hold  0.000107      0.998123   
3       BubbleStocks  61.111111       Hold  0.000207      0.998539   
4        OkayFinance  66.666667       Hold  0.192000      0.998542   
...              ...        ...        ...       ...           ...   
490641  BubbleStocks  61.643836       Hold  0.009000      1.000498   
490642      BigStock  43.820225       Hold  0.010067      1.000521   
490643    HeroStocks  25.842697        Buy  0.000900      1.001464   
490644  BubbleStocks  42.857143       Hold  0.000001      1.000001   
490645   OkayFinance  25.000000        Buy  0.000187      1.006669   

        MA_relative  SMA_relative  WMA_relative          MACD  MACD_relative  \
0          0.998415      0.158790      0.000696  6.538214e-04       0.000990   
1          0.999907      0.009270      0.000069 -7.055833e-03      -0.000058   
2          0.997812      0.219298      0.001863 -2.793596e-05      -0.000611   
3          0.998178      0.182580      0.001528  5.317996e-05       0.000260   
4          0.998191      0.181218      0.001477  1.408120e-01       0.001585   
...             ...           ...           ...           ...            ...   
490641     0.999683      0.031746     -0.000637  6.019700e-03       0.000955   
490642     1.000697     -0.069696     -0.000529 -6.117755e-03      -0.000464   
490643     1.002397     -0.239088     -0.001392 -1.064041e-03      -0.001128   
490644     1.000332     -0.033156      0.000124 -9.036562e-07      -0.002248   
490645     1.007683     -0.762477     -0.006755 -1.133429e-04      -0.001319   

        ...  Bollinger_signal  ichimoku_c_conversion_line  \
0       ...              Hold                   -0.166616   
1       ...              Hold                   -0.012268   
2       ...              Hold                   -0.328228   
3       ...              Hold                   -0.231877   
4       ...              Hold                   -0.140734   
...     ...               ...                         ...   
490641  ...              Hold                    0.047604   
490642  ...              Hold                    0.064438   
490643  ...              Hold                    0.111347   
490644  ...              Hold                   -0.248756   
490645  ...               Buy                    0.640279   

        ichimoku_c_base_line  ichimoku_c_leading_span_a  \
0                  -0.181763                  -0.602090   
1                  -0.024536                  -0.292386   
2                  -0.109409                   0.109409   
3                  -0.183061                  -0.170857   
4                  -0.613601                  -0.529160   
...                      ...                        ...   
490641             -0.015868                  -0.182482   
490642              0.121295                   0.109923   
490643              0.121951                  -0.037116   
490644              0.248756                   1.057214   
490645              0.698487                   0.552969   

        ichimoku_c_leading_span_b  ichimoku_c_signal  SAR_relative  \
0                       -0.446834               Sell     -0.136418   
1                       -0.155394               Sell     -0.006776   
2                       -0.656455                Buy     -0.143955   
3                       -0.414938                Buy     -0.192382   
4                        1.339788               Sell     -0.199855   
...                           ...                ...           ...   
490641                   0.364964               Sell      0.018308   
490642                   0.003790                Buy      0.078080   
490643                  -0.371156                Buy      0.303781   
490644                   1.616915               Sell      0.098221  

## Bringing dependent variable column at the end

In [90]:
idcol = df['id']
idcol

0         573919
1         292589
2          80399
3         109870
4         289641
           ...  
490641    110269
490642    259179
490643    365839
490644    131933
490645    121959
Name: id, Length: 490646, dtype: int64

In [91]:
df.drop('id', inplace = True, axis = 1)

In [92]:
resultcol = df['result']
resultcol

0         2
1         2
2         1
3         1
4         2
         ..
490641    1
490642    2
490643    2
490644    2
490645    2
Name: result, Length: 490646, dtype: int64

In [93]:
df.drop('result', inplace = True, axis = 1)

In [94]:
df.shape

(490646, 38)

In [95]:
df['id'] = idcol

In [96]:
df['result'] = resultcol

In [97]:
df.head()

exchange        RSI RSI_signal       ATR  EMA_relative  MA_relative  \
0      BigStock  60.176991       Hold  0.001340      0.999133     0.998415   
1    HeroStocks  30.000000        Buy  0.009333      0.999927     0.999907   
2   OkayFinance  45.454545       Hold  0.000107      0.998123     0.997812   
3  BubbleStocks  61.111111       Hold  0.000207      0.998539     0.998178   
4   OkayFinance  66.666667       Hold  0.192000      0.998542     0.998191   

   SMA_relative  WMA_relative      MACD  MACD_relative  ...  Bollinger_signal  \
0      0.158790      0.000696  0.000654       0.000990  ...              Hold   
1      0.009270      0.000069 -0.007056      -0.000058  ...              Hold   
2      0.219298      0.001863 -0.000028      -0.000611  ...              Hold   
3      0.182580      0.001528  0.000053       0.000260  ...              Hold   
4      0.181218      0.001477  0.140812       0.001585  ...              Hold   

   ichimoku_c_conversion_line  ichimoku_c_base_line  \
0                   -0.166616             -0.181763   
1                   -0.012268             -0.024536   
2                   -0.328228             -0.109409   
3                   -0.231877             -0.183061   
4                   -0.140734             -0.613601   

   ichimoku_c_leading_span_a  ichimoku_c_leading_span_b  ichimoku_c_signal  \
0                  -0.602090                  -0.446834               Sell   
1                  -0.292386                  -0.155394               Sell   
2                   0.109409                  -0.656455                Buy   
3                  -0.170857                  -0.414938                Buy   
4                  -0.529160                   1.339788               Sell   

   SAR_relative s&p_move_15m      id  result  
0     -0.136418     0.252291  573919       2  
1     -0.006776     0.062449  292589       2  
2     -0.143955     0.616755   80399       1  
3     -0.192382     0.343096  109870       1  
4     -0.199855    -0.352336  289641       2  

[5 rows x 40 columns]

## Encoding all categorical columns using Label Encoder

In [98]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['RSI_signal'] = le.fit_transform(df['RSI_signal'])
df['Stoch_O_signal'] = le.fit_transform(df['Stoch_O_signal'])
df['ichimoku_c_signal'] = le.fit_transform(df['ichimoku_c_signal'])
df['fibonacci_signal'] = le.fit_transform(df['fibonacci_signal'])
df['Bollinger_signal'] = le.fit_transform(df['Bollinger_signal'])

In [99]:
df.head(15)

exchange        RSI  RSI_signal       ATR  EMA_relative  MA_relative  \
0       BigStock  60.176991           1  0.001340      0.999133     0.998415   
1     HeroStocks  30.000000           0  0.009333      0.999927     0.999907   
2    OkayFinance  45.454545           1  0.000107      0.998123     0.997812   
3   BubbleStocks  61.111111           1  0.000207      0.998539     0.998178   
4    OkayFinance  66.666667           1  0.192000      0.998542     0.998191   
5   BubbleStocks  40.000000           1  0.026667      0.999810     1.000292   
6       BigStock  76.800000           2  0.002053      0.999998     0.999552   
7    OkayFinance   0.000000           0  0.000733      1.011476     1.013252   
8       BigStock  55.555556           1  0.001533      1.002343     1.002415   
9       BigStock  40.000000           1  0.034000      0.999985     1.000199   
10    HeroStocks  69.166667           1  0.001767      0.999643     0.999006   
11  BubbleStocks  55.000000           1  0.000753      1.000340     1.000390   
12      BigStock  45.661954           1  0.057700      0.997271     0.997552   
13      BigStock  56.603774           1  0.065333      0.999795     0.999755   
14      BigStock  47.755102           1  0.281333      0.998507     0.998653   

    SMA_relative  WMA_relative      MACD  MACD_relative  ...  \
0       0.158790      0.000696  0.000654       0.000990  ...   
1       0.009270      0.000069 -0.007056      -0.000058  ...   
2       0.219298      0.001863 -0.000028      -0.000611  ...   
3       0.182580      0.001528  0.000053       0.000260  ...   
4       0.181218      0.001477  0.140812       0.001585  ...   
5      -0.029189      0.000316 -0.022209      -0.000648  ...   
6       0.044784     -0.000068  0.002362       0.001602  ...   
7      -1.307847     -0.011512 -0.000706      -0.002161  ...   
8      -0.240888     -0.002487  0.000874       0.001376  ...   
9      -0.019911      0.000066 -0.025458      -0.000634  ...   
10      0.099472      0.000223  0.002095       0.002096  ...   
11     -0.038955     -0.000356  0.000407       0.000433  ...   
12      0.245384      0.002792 -0.004682      -0.000374  ...   
13      0.024508      0.000221  0.040773       0.000258  ...   
14      0.134914      0.001599 -0.180198      -0.001160  ...   

    Bollinger_signal  ichimoku_c_conversion_line  ichimoku_c_base_line  \
0                  1                   -0.166616             -0.181763   
1                  1                   -0.012268             -0.024536   
2                  1                   -0.328228             -0.109409   
3                  1                   -0.231877             -0.183061   
4                  1                   -0.140734             -0.613601   
5                  1                   -0.072993              0.000000   
6                  1                    0.027130             -0.301818   
7                  0                    1.070336              1.070336   
8                  1                    0.236220             -0.078740   
9                  1                   -0.024894              0.099577   
10                 1                   -0.030012             -0.450180   
11                 1                    0.053141             -0.100967   
12                 1                   -0.336664             -0.433710   
13                 1                   -0.022179             -0.079209   
14                 1                   -0.292849              0.141597   

    ichimoku_c_leading_span_a  ichimoku_c_leading_span_b  ichimoku_c_signal  \
0                   -0.602090                  -0.446834                  2   
1                   -0.292386                  -0.155394                  2   
2                    0.109409                  -0.656455                  0   
3                   -0.170857                  -0.414938                  0   
4                   -0.529160                   1.339788                  2   
5                    0.000000              

# Splitting Data into X and y

In [100]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

# Applying One Hot Encoding to a Categorical Column

In [101]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [102]:
print(X)

[[1.0 0.0 0.0 ... -0.1364176201869291 0.2522906299921071 573919]
 [0.0 0.0 1.0 ... -0.0067759512435203 0.0624487986999857 292589]
 [0.0 0.0 0.0 ... -0.1439545782103735 0.6167551035448348 80399]
 ...
 [0.0 0.0 1.0 ... 0.3037812594246464 0.0267505069386263 365839]
 [0.0 1.0 0.0 ... 0.0982206752018254 0.1909386816210215 131933]
 [0.0 0.0 0.0 ... 0.874831278063297 -0.3142787445112997 121959]]


#Splitting data into Test and Training set

In [103]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 1)

#Applying Feature Scaling

In [104]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Predicting the model using Random Forest Classifier

In [105]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0, max_depth = 15)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', max_depth=15, random_state=0)

In [106]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[2 2]
 [2 2]
 [2 2]
 ...
 [2 2]
 [2 2]
 [2 2]]


In [107]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  7813      1      0]
 [     0  20467      1]
 [     0      0 118912]]


0.9999864124896395

#TEST DATA

In [108]:
testdf = pd.read_csv('test.csv')
testdf.head()

exchange        RSI RSI_signal       ATR  EMA_relative  MA_relative  \
0     BigStock  43.478261       Hold  0.000047      0.999783     1.000338   
1  OkayFinance  60.869565       Hold  0.007800      0.994304     0.993500   
2  OkayFinance  89.473684       Sell  0.000023      0.999171     0.998335   
3  OkayFinance  41.891892       Hold  0.100000      0.999145     0.999414   
4   HeroStocks  53.367876       Hold  0.016333      1.000864     1.000520   

   SMA_relative  WMA_relative      MACD  MACD_relative  ...  \
0     -0.033829      0.000238 -0.000053      -0.003367  ...   
1      0.654291      0.005838  0.001707       0.000645  ...   
2      0.166814      0.000700  0.000053       0.002085  ...   
3      0.058674      0.000945 -0.035090      -0.000401  ...   
4     -0.051951     -0.001008  0.002869       0.000386  ...   

   Bollinger_lower_band  Bollinger_signal  ichimoku_c_conversion_line  \
0             -0.010565              Hold                   -0.063452   
1             -0.000386              Hold                   -0.642479   
2             -0.000553              Hold                   -0.117096   
3             -0.002394              Hold                   -0.165639   
4             -0.009193              Hold                    0.181476   

   ichimoku_c_base_line  ichimoku_c_leading_span_a  ichimoku_c_leading_span_b  \
0              0.571066                   1.729061                   1.967005   
1             -0.566893                  -0.255102                  -0.132275   
2             -0.351288                  -0.634270                  -0.644028   
3             -0.085675                   0.105666                   0.428376   
4              0.094099                   1.008200                   1.102299   

   ichimoku_c_signal SAR_relative  s&p_move_15m      id  
0               Sell     0.107612     -1.333366    4049  
1               Sell    -0.725446     -0.050090  292873  
2                Buy    -0.117630      0.182169   80893  
3               Sell    -0.143443     -0.001095  246380  
4               Sell     0.072801     -0.133143  145977  

[5 rows x 39 columns]

In [109]:
testdf.isnull().sum()

exchange                      0
RSI                           0
RSI_signal                    0
ATR                           0
EMA_relative                  0
MA_relative                   0
SMA_relative                  0
WMA_relative                  0
MACD                          0
MACD_relative                 0
MACD_relative_signal          0
MACD_relative_histogram       0
ADX                           0
Stoch_O_k_value               0
Stoch_O_k_smoothed            0
Stoch_O_d_value               0
Stoch_O_signal_value          0
Stoch_O_signal                0
pivot_point                   0
pivot_support_1               0
pivot_resistance_1            0
pivot_support_2               0
pivot_resistance_2            0
pivot_support_3               0
pivot_resistance_3            0
fibonacci_signal              0
VWAP_relative_short           0
VWAP_relative_long            0
Bollinger_upper_band          0
Bollinger_lower_band          0
Bollinger_signal              0
ichimoku

In [110]:
testdf.shape

(122662, 39)

In [111]:
testidcol = testdf['id']

# Data Preprocessing phase for Test DataSet

## Applying label encoding to test data set

In [112]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
testdf['RSI_signal'] = le.fit_transform(testdf['RSI_signal'])
testdf['Stoch_O_signal'] = le.fit_transform(testdf['Stoch_O_signal'])
testdf['ichimoku_c_signal'] = le.fit_transform(testdf['ichimoku_c_signal'])
testdf['fibonacci_signal'] = le.fit_transform(testdf['fibonacci_signal'])
testdf['Bollinger_signal'] = le.fit_transform(testdf['Bollinger_signal'])

In [113]:
X_2 = testdf.iloc[:, 0:].values

## Applying One Hot Encoding to 'exchange' column

In [114]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X_2 = np.array(ct.fit_transform(X_2))

In [115]:
print(X_2)

[[1.0 0.0 0.0 ... 0.1076124772169284 -1.3333663537977698 4049]
 [0.0 0.0 0.0 ... -0.725446307953642 -0.0500897061100334 292873]
 [0.0 0.0 0.0 ... -0.1176299004229701 0.1821691821691873 80893]
 ...
 [1.0 0.0 0.0 ... -0.1645271099337675 0.1567899167339013 59169]
 [0.0 0.0 0.0 ... 0.1526675026340636 0.0922281989150214 287199]
 [0.0 0.0 1.0 ... -0.2005514942585184 -0.0900627682354063 223041]]


## Applying feature scaling to test dataset

In [116]:
from sklearn.preprocessing import StandardScaler
sc_test = StandardScaler()
X_2 = sc_test.fit_transform(X_2)

# Predicting the test set results using above random forest classifier

In [117]:
y_pred_test = classifier.predict(X_2)

In [118]:
print(y_pred_test)

[0 2 1 ... 1 2 2]


In [119]:
print(testidcol)

0           4049
1         292873
2          80893
3         246380
4         145977
           ...  
122657     97614
122658    189089
122659     59169
122660    287199
122661    223041
Name: id, Length: 122662, dtype: int64


# Appending the predicted result to the final sheet

In [120]:
to_append = pd.DataFrame(y_pred_test, columns = ['result'])

In [121]:
answer = pd.concat([testidcol, to_append] ,axis= 1)
print(answer)

            id  result
0         4049       0
1       292873       2
2        80893       1
3       246380       2
4       145977       2
...        ...     ...
122657   97614       1
122658  189089       2
122659   59169       1
122660  287199       2
122661  223041       2

[122662 rows x 2 columns]


In [122]:
answer.to_csv("submission.csv",index=False)